{% set name = "chalk-diagrams" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2c7ebebc4c09d00a27d91955d9294962fa0ea676b2a3d098ac3d22b3b6e70af0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - cairosvg
    - colour
    - pillow
    - pycairo
    - svgwrite
    - toolz

test:
  imports:
    - chalk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/danoneata/chalk
  summary: A declarative drawing API
  license: MIT
  license_file: LICENSE
  description: |
    Chalk is a declarative drawing library built on top of [PyCairo](https://pycairo.readthedocs.io).
    The API draws heavy inspiration from
    Haskell's [diagrams](https://diagrams.github.io/),
    Scala's [doodle](https://github.com/creativescala/doodle/) and
    Jeremy Gibbons's lecture notes on 
    [Functional Programming for Domain−Specific Languages](http://www.cs.ox.ac.uk/publications/publication7583-abstract.html).

    PyPI: [https://pypi.org/project/chalk-diagrams](https://pypi.org/project/chalk-diagrams)

  doc_url: https://github.com/danoneata/chalk
  dev_url: https://github.com/danoneata/chalk

extra:
  recipe-maintainers:
    - sugatoray
